$(document).ready(function(){
    $(".owl-carousel").owlCarousel({
        loop:true,
      margin:200,
      nav:false,
      autoplay:false,
      dotsEach:true,
  //    dots:false,
      autoplayHoverPause:true,
      responsive:{
          0:{
              items:1
          },
          600:{
              items:2
          },
          1000:{
              items:3
          }
      }
    });
  });  